### ISSUE TITLE
the program can't run

### ISSUE THREAD

**Issue by heucoder** [snowkylin/line#11]
Traceback (most recent call last):
  File "line.py", line 69, in <module>
    main()
  File "line.py", line 23, in main
    train(args)
  File "line.py", line 29, in train
    data_loader = DBLPDataLoader(graph_file=args.graph_file)
  File "/home/yt/yantao/研究生课程/降维-可视化/LINE_code/line-master/utils.py", line 8, in __init__
    self.num_of_nodes = self.g.number_of_nodes()
  File "/usr/local/lib/python3.6/site-packages/networkx/classes/graph.py", line 798, in number_of_nodes
    return len(self._node)
AttributeError: 'Graph' object has no attribute '_node'
can you tell me how to solve this problem?

**Comment by xiongweii** [comment]
This is because your version is new,but the code version is older.You could uninstall networkx and reinstall by pip install networkx==1.9.1
